language: c++
compiler: clang
os: osx
osx_image: xcode7.3
before_install:
  - brew tap homebrew/science
  - brew update
  - brew outdated cmake || brew upgrade cmake
  - brew outdated boost || brew upgrade boost
  - brew install eigen
  - brew install freeimage
  - brew install glog
  - brew install gflags
  - brew install suite-sparse
  - brew install ceres-solver
  - brew install qt5
  - brew install glew
install:
  - echo 'set(Qt5_CMAKE_DIR "/usr/local/opt/qt5/lib/cmake")' >  LocalConfig.cmake
  - echo 'set(Qt5Core_DIR ${Qt5_CMAKE_DIR}/Qt5Core)'         >> LocalConfig.cmake
  - echo 'set(Qt5OpenGL_DIR ${Qt5_CMAKE_DIR}/Qt5OpenGL)'     >> LocalConfig.cmake
  - mkdir build && pushd build
  - cmake ..
  - make -j
