language: c++
matrix:
  include:
  - os: osx
    osx_image: xcode7.3
    compiler: clang
    before_install: scripts/shell/ci/before-install-macos.sh
    install: scripts/shell/ci/install-macos.sh
deploy:
  provider: releases
  api_key:
    secure: dG052Nwa7+1COPUCoLASTd42xbym8zBnkb2aaWCnO/fJbmqcrqkFQ5HKZ2S/HHiLt2tb4CUfJze16gouSKPdCfdgUshmcodN3PivLwsCkLZs+yiDN6Rq2a5dYJ7StH4EaGA2OlqdPFIvh8mnuY0LFFVVzNrS2kg75YVzpTL7RH+OlXk3fZ0+YR324BFidRaad1bRnEb8yIF21X+ik4EbScefLCYIzAFyj+uUWe0OrlUMZ4uSajinkSCjSGFJTgqfbCGtuiINp0O0SlYaV7+Rgisi4vbOIjnPGwJPXXp2qM4h3HAXinsTZw7j5xJaOqfQXa0BMPE7XnRec4qRYBdkaWJ/CHUjAZHeD1HAE58CbJir9L6ZxW+d90Swr8l8ExZn/NJT2+FgHurjqf/nbbowjT6ogJ+iifRTINJKSgio3byUXItDiJjwgOu+MZ1wkyMBd0+Ze/nYp+y5mBL6njebW4CHDloFlxdsrSGdW2Qg8mKq48gE4MNM/0b9X8gnzvlnjtbcd9W1d5saRktchKbMueTy5YgqCQEXtfZz50x+lAh2J3oezT98e2k07EQRF9DJr5BHhFwobxJAzBWDBarnOlDksz8tp86CbrmCsQWTKO4efB/O8fs0oCkrNp8RBUToSFzQRyHcdkC5QsAETFQZJsunEIc7JwQzMn0mNkLvud0=
  file: colmap.dmg
  on:
    repo: lancelet/colmap
    branch: travis-macos
