language: c++

# Additional build platforms can be added to this matrix.
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      before_install: scripts/shell/ci/before-install-macos.sh
      install: scripts/shell/ci/install-macos.sh
